export const PLAN_STATUS = { DRAFT: 'DRAFT', CONFIRMED: 'CONFIRMED', ARCHIVED: 'ARCHIVED' } as const
export const MEAL_TYPE = { BREAKFAST: 'BREAKFAST', LUNCH: 'LUNCH', DINNER: 'DINNER' } as const
export const CROWD_TYPE = { FAMILY: 'FAMILY', WIFE: 'WIFE', HUSBAND: 'HUSBAND', BABY: 'BABY', WIFE_WEIGHT_LOSS: 'WIFE_WEIGHT_LOSS' } as const
